# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e134f1c88e760867d0bba7293de8f3a149f71d540102b69db98a4bc048fe45e8dc64f316028c1cfdce524ec1612dd3093ce0b7a8575b7573694c13a4cda16cee

test:
  secret_key_base: 524926f41f92a0405ae77b279a0ecfc6e04bfa3453809f813986507bd3fbe83ea36a470678491dc6a512191fb35a6055d5f193f3d8b34435762ba63bcce33591

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
